version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "efun_postgres"
    ports:
      - "54320:5432"
    volumes:
      - ./efun_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
